name: another_carousel_pro
description: A nulll safe version of flutter-carasoul-pro package.
version: 1.0.0
homepage: https://github.com/iamnabink/another_carousel_pro
license: MIT
issue_tracker: https://github.com/iamnabink/another_carousel_pro/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
